### ISSUE TITLE
Not automatically refresh the html page when the new message arrives

### ISSUE THREAD

**Issue by ngu0029** [ngu0029/mq-app#1]
I am still facing the issue of not automatically changing the new message on the html page.
One more thing, I use the localhost:443 for simply testing HTTP Post (curl command) on my localhost instead of SSL web server.
I hope I will fix the issues soon.

Please refer to the readme file for setup and test instructions. I have tested on my Windonws 10 laptop.

cc @olivernadj

Thanks,

**Comment by olivernadj** [comment]
Thanks @ngu0029 for your submission.

**Comment by ngu0029** [comment]
I have fixed the issue of not automatically changing the new message on the html page

cc @olivernadj

Thanks,

**Comment by ngu0029** [comment]
I have updated the README file for one shot setup with bash script.

cc @olivernadj

Thanks,
